// DataCite- and Zenodo-shaped deposit metadata (§15). Suggested/provisional
// mapping, not a normative external schema — the base workflow never calls
// Zenodo's API, so this only has to be good enough to paste into the
// deposit form or a future automated deposit.

import type { AirRecord } from "./model.js";

export function generateDataCiteMetadata(record: AirRecord) {
  const year = new Date(record.capture.captured_at).getUTCFullYear();
  return {
    types: { resourceTypeGeneral: "Dataset", resourceType: "AI Interaction" },
    titles: [{ title: record.title }],
    creators:
      record.creator.length > 0
        ? record.creator.map((c) => ({
            name: c.name,
            ...(c.orcid ? { nameIdentifiers: [{ nameIdentifier: c.orcid, nameIdentifierScheme: "ORCID" }] } : {}),
          }))
        : [{ name: "(unspecified)" }],
    publicationYear: year,
    dates: [
      ...(record.conversation_created_at
        ? [{ date: record.conversation_created_at, dateType: "Created" }]
        : []),
      { date: record.capture.captured_at, dateType: "Captured" },
    ],
    rightsList: record.license ? [{ rights: record.license }] : [],
    relatedIdentifiers: [
      ...(record.source_uri
        ? [{ relatedIdentifier: record.source_uri, relatedIdentifierType: "URL", relationType: "IsDerivedFrom" }]
        : []),
      ...record.related.map((r) => ({
        relatedIdentifier: r.identifier,
        relatedIdentifierType: guessIdentifierType(r.identifier),
        relationType: toDataCiteRelation(r.relation),
      })),
    ],
    subjects: record.keywords.map((k) => ({ subject: k })),
    version: record.air_version,
    description: record.description ?? undefined,
  };
}

export function generateZenodoMetadata(record: AirRecord) {
  return {
    metadata: {
      title: record.title,
      upload_type: "dataset",
      description:
        record.description ??
        "AI Interaction Record (AIR) archival package generated by chat2archive.",
      creators:
        record.creator.length > 0
          ? record.creator.map((c) => ({ name: c.name, ...(c.orcid ? { orcid: c.orcid } : {}) }))
          : [{ name: "(unspecified)" }],
      keywords: [...record.keywords, "AIR", "chat2archive", "AI interaction record"],
      license: record.license ?? undefined,
      related_identifiers: [
        ...(record.source_uri
          ? [{ identifier: record.source_uri, relation: "isDerivedFrom", resource_type: "other" }]
          : []),
        ...record.related.map((r) => ({
          identifier: r.identifier,
          relation: toZenodoRelation(r.relation),
          resource_type: "dataset",
        })),
      ],
      version: record.air_version,
    },
  };
}

function toDataCiteRelation(relation: string): string {
  const map: Record<string, string> = {
    continuedFrom: "Continues",
    isVersionOf: "IsVersionOf",
    hasVersion: "HasVersion",
    isDerivedFrom: "IsDerivedFrom",
    isSourceOf: "IsSourceOf",
    relatedPublication: "IsReferencedBy",
  };
  return map[relation] ?? "IsRelatedTo";
}

function toZenodoRelation(relation: string): string {
  const map: Record<string, string> = {
    continuedFrom: "continues",
    isVersionOf: "isVersionOf",
    hasVersion: "hasVersion",
    isDerivedFrom: "isDerivedFrom",
    isSourceOf: "isSourceOf",
    relatedPublication: "isReferencedBy",
  };
  return map[relation] ?? "isRelatedTo";
}

function guessIdentifierType(identifier: string): string {
  if (/^10\.\d{4,9}\//.test(identifier)) return "DOI";
  if (/^https?:\/\//.test(identifier)) return "URL";
  return "Other";
}
