// Assembles a complete AIR package (files + bytes) from a canonical
// AirRecord. Shared, unchanged, between the CLI and the browser: the only
// difference is what the caller does with the returned file map (write to
// disk vs. trigger a download).

import { zipSync, type Zippable } from "fflate";
import type { AirRecord } from "./model.js";
import { canonicalEventsJsonl, sha256HexOfString } from "./hash.js";
import { normalizeRecord, computeStats, type ArchiveStats } from "./normalize.js";
import { renderTranscriptMarkdown, renderTranscriptHtml } from "./transcript.js";
import { renderInteractionMarkdown, type DatasheetNotes } from "./datasheet.js";
import { generateRoCrateMetadata, type PackagedFile } from "./rocrate.js";
import { generateDataCiteMetadata, generateZenodoMetadata } from "./datacite.js";
import { validatePackageFiles } from "./validate.js";

export interface PackageOptions {
  datasheetNotes?: DatasheetNotes;
}

export interface BuiltPackage {
  /** Path relative to the package root (e.g. "air-record/"), to file bytes. */
  files: Map<string, Uint8Array>;
  record: AirRecord;
  stats: ArchiveStats;
  warnings: string[];
}

function sortKeysDeep(value: unknown): unknown {
  if (Array.isArray(value)) return value.map(sortKeysDeep);
  if (value !== null && typeof value === "object") {
    const out: Record<string, unknown> = {};
    for (const key of Object.keys(value as Record<string, unknown>).sort()) {
      out[key] = sortKeysDeep((value as Record<string, unknown>)[key]);
    }
    return out;
  }
  return value;
}

function prettyJson(value: unknown): string {
  return JSON.stringify(sortKeysDeep(value), null, 2) + "\n";
}

function airJsonOf(record: AirRecord) {
  return {
    air_version: record.air_version,
    title: record.title,
    creator: record.creator,
    conversation_created_at: record.conversation_created_at,
    capture_created_at: record.capture_created_at,
    provider: record.provider,
    source_uri: record.source_uri,
    license: record.license,
    keywords: record.keywords,
    description: record.description,
    selection: record.selection,
    capture: record.capture,
    agents: record.agents,
    related: record.related,
    canonical_sha256: record.canonical_sha256,
  };
}

function readmeText(record: AirRecord, stats: ArchiveStats): string {
  return `# ${record.title}

This is an AIR (AI Interaction Record) archival package generated by
[chat2archive](https://github.com/MartinuzziFrancesco/chat2archive), version
${record.capture.capture_software}. It packages one AI conversation as a
provider-neutral, citable research object (AIR-compatible RO-Crate,
protocol version ${record.air_version}).

## Contents

- \`conversation.jsonl\` — the normative event log (authoritative)
- \`air.json\` — record metadata, validated against \`schema/air-0.1.schema.json\`
- \`ro-crate-metadata.json\` — RO-Crate / JSON-LD package description
- \`transcript.md\` / \`transcript.html\` — human-readable renderings (not authoritative)
- \`INTERACTION.md\` — an interaction datasheet describing how this was captured
- \`datacite.json\` / \`zenodo.json\` — suggested deposit metadata
- \`SHA256SUMS\` — integrity hashes for every file in this package

## Summary

- Messages: ${stats.messageCount}
- Branches: ${stats.branchCount}
- Tool calls: ${stats.toolCallCount}
- Attachments: ${stats.attachmentCount}
- Provider: ${record.provider ?? "unknown"}
- Capture class: ${record.capture.class}

## Uploading to Zenodo

1. Create a new upload at https://zenodo.org/deposit/new.
2. Upload this ZIP file (or its contents) as the deposit files.
3. Copy fields from \`datacite.json\` / \`zenodo.json\` into the deposit form —
   title, creators, keywords, related identifiers, and license.
4. Set the resource type to "Dataset".
5. Publish. Zenodo assigns and preserves the DOI; chat2archive does not.

## Integrity

Every file's SHA-256 hash is listed in \`SHA256SUMS\`. A hash proves the
archived bytes are unchanged since hashing — it does not prove the original
conversation is authentic or complete. See \`INTERACTION.md\` for what was and
was not captured.
`;
}

export async function buildPackage(record: AirRecord, opts: PackageOptions = {}): Promise<BuiltPackage> {
  const { warnings } = normalizeRecord(record);
  const stats = computeStats(record.events);

  const conversationJsonl = canonicalEventsJsonl(record.events);
  const canonicalSha256 = await sha256HexOfString(conversationJsonl);
  const finalRecord: AirRecord = { ...record, canonical_sha256: canonicalSha256 };

  const encoder = new TextEncoder();
  const textFiles = new Map<string, string>();

  textFiles.set("air.json", prettyJson(airJsonOf(finalRecord)));
  textFiles.set("conversation.jsonl", conversationJsonl);
  textFiles.set("transcript.md", renderTranscriptMarkdown(finalRecord, stats));
  textFiles.set("transcript.html", renderTranscriptHtml(finalRecord, stats));
  textFiles.set("INTERACTION.md", renderInteractionMarkdown(finalRecord, stats, opts.datasheetNotes));
  textFiles.set("datacite.json", prettyJson(generateDataCiteMetadata(finalRecord)));
  textFiles.set("zenodo.json", prettyJson(generateZenodoMetadata(finalRecord)));
  textFiles.set("README.md", readmeText(finalRecord, stats));

  // ro-crate-metadata.json describes the other files (with their hashes), so
  // it must be generated after everything else, and is itself hashed and
  // listed in SHA256SUMS like any other file.
  const packagedFiles: PackagedFile[] = [];
  for (const [path, content] of textFiles) {
    packagedFiles.push({ path, sha256: await sha256HexOfString(content), contentType: contentTypeFor(path) });
  }
  const rocrate = generateRoCrateMetadata(finalRecord, packagedFiles);
  const rocrateText = prettyJson(rocrate);
  textFiles.set("ro-crate-metadata.json", rocrateText);
  packagedFiles.push({
    path: "ro-crate-metadata.json",
    sha256: await sha256HexOfString(rocrateText),
    contentType: "application/ld+json",
  });

  const sumLines = packagedFiles
    .slice()
    .sort((a, b) => a.path.localeCompare(b.path))
    .map((f) => `${f.sha256}  ${f.path}`);
  textFiles.set("SHA256SUMS", sumLines.join("\n") + "\n");

  const files = new Map<string, Uint8Array>();
  for (const [path, content] of textFiles) {
    files.set(path, encoder.encode(content));
  }

  // Self-check before handing the archive to the caller: a package that fails
  // its own published schema is a chat2archive bug, not a user-facing warning.
  const selfCheck = await validatePackageFiles(files);
  if (!selfCheck.valid) {
    throw new Error(`Internal error: the built package failed its own validation: ${selfCheck.errors.join("; ")}`);
  }

  return { files, record: finalRecord, stats, warnings };
}

/** Filesystem/URL-safe slug for a record title, used as the default archive filename. */
export function slugify(title: string): string {
  return (
    title
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, "-")
      .replace(/(^-|-$)/g, "")
      .slice(0, 60) || "air-record"
  );
}

function contentTypeFor(path: string): string {
  if (path.endsWith(".json")) return "application/json";
  if (path.endsWith(".jsonl")) return "application/jsonl";
  if (path.endsWith(".md")) return "text/markdown";
  if (path.endsWith(".html")) return "text/html";
  return "application/octet-stream";
}

// ZIP's DOS date field cannot represent years before 1980; use a fixed,
// arbitrary in-range timestamp so packaging the same record twice produces
// byte-identical ZIPs (§30 of instructions.md).
const DETERMINISTIC_MTIME = new Date(Date.UTC(1980, 0, 1));

/** Zips a built package's files under a single `air-record/` root, deterministically. */
export function zipPackage(built: BuiltPackage): Uint8Array {
  const tree: Zippable = {};
  for (const [path, content] of [...built.files].sort(([a], [b]) => a.localeCompare(b))) {
    tree[`air-record/${path}`] = [content, { mtime: DETERMINISTIC_MTIME, level: 6 }];
  }
  return zipSync(tree, { mtime: DETERMINISTIC_MTIME });
}

