// RO-Crate metadata generation — an "AIR Profile of RO-Crate" (§14).
// Uses standard RO-Crate 1.1 / schema.org vocabulary; AIR-specific facts
// that have no established term live under an `air:` namespace instead of
// overloading an existing property with a different meaning.

import type { AirRecord } from "./model.js";

export interface PackagedFile {
  path: string;
  sha256: string;
  contentType?: string;
}

const AIR_CONTEXT = "https://chat2archive.dev/schema/air-0.1-context.jsonld";

export function generateRoCrateMetadata(record: AirRecord, files: PackagedFile[]) {
  const creators = record.creator.map((c, i) => ({
    "@id": c.orcid ? normalizeOrcid(c.orcid) : `#creator-${i + 1}`,
    "@type": "Person",
    name: c.name,
    ...(c.orcid ? { identifier: normalizeOrcid(c.orcid) } : {}),
  }));

  const agents = record.agents.map((a) => ({
    "@id": `#${a.id}`,
    "@type": "SoftwareApplication",
    name: a.name ?? a.id,
    "air:model": a.model.name,
    "air:modelProvider": a.model.provider,
    "air:modelEvidence": a.model.evidence,
  }));

  const fileEntities = files.map((f) => ({
    "@id": f.path,
    "@type": "File",
    sha256: f.sha256,
    ...(f.contentType ? { encodingFormat: f.contentType } : {}),
  }));

  const rootDataset: Record<string, unknown> = {
    "@id": "./",
    "@type": "Dataset",
    name: record.title,
    description:
      "AIR (AI Interaction Record) archival package generated by chat2archive: a provider-neutral, " +
      "citable research object for one AI conversation.",
    datePublished: record.capture.captured_at,
    ...(record.conversation_created_at ? { dateCreated: record.conversation_created_at } : {}),
    ...(record.license ? { license: record.license } : {}),
    ...(record.source_uri ? { isBasedOn: { "@id": record.source_uri } } : {}),
    creator: creators.map((c) => ({ "@id": c["@id"] })),
    "air:agent": agents.map((a) => ({ "@id": a["@id"] })),
    hasPart: files.map((f) => ({ "@id": f.path })),
    "air:version": record.air_version,
    "air:captureClass": record.capture.class,
    "air:canonicalSha256": record.canonical_sha256 ?? null,
    ...(record.related.length > 0
      ? {
          "air:related": record.related.map((r) => ({
            "air:relation": r.relation,
            "air:identifier": r.identifier,
          })),
        }
      : {}),
  };

  return {
    "@context": ["https://w3id.org/ro/crate/1.1/context", { air: AIR_CONTEXT }],
    "@graph": [
      {
        "@id": "ro-crate-metadata.json",
        "@type": "CreativeWork",
        conformsTo: { "@id": "https://w3id.org/ro/crate/1.1" },
        about: { "@id": "./" },
        "air:profile": "AIR-0.1",
      },
      rootDataset,
      ...creators,
      ...agents,
      ...fileEntities,
    ],
  };
}

function normalizeOrcid(orcid: string): string {
  return orcid.startsWith("http") ? orcid : `https://orcid.org/${orcid}`;
}
